In [4]:
def userInfo(name,email,userList=[]):
    print(name,email)
    userList.append(name)
    return {"name":name, "email":email,"userList":userList}
u1=userInfo("tushar","tusj@gmail.com")
u2=userInfo("zee","zee@gmail.com")
print(u2)

tushar tusj@gmail.com
zee zee@gmail.com
{'name': 'zee', 'email': 'zee@gmail.com', 'userList': ['tushar', 'zee']}


In [12]:
from abc import ABC,abstractmethod
class A(ABC):
    @abstractmethod
    def dept(self):
        pass
class B(A):
    def dept(self):
        pass
b=B()
b.dept()

In [16]:
class Currency:
    amount=20
    def __repr__(self):
        return f"Currencyis {Currency.amount}"
    def changeCurrency(rupees):
        return Currency.amount+rupees
print(Currency.changeCurrency(100))
    

120


In [21]:
class Yen:
    def __init__(self,amount):
        self.amount=amount
        self.symbol="¥"
    def __repr__(self):
        return f"Currency class {self.symbol}:{self.amount}"
y=Yen(100)
print(y)

Currency class ¥:100


Implementing class method

In [23]:
class Currency:
    def __init__(self,amount):
        self.amount=amount
    def __repr__(self):
        return f" Currency is ${self.amount}"
    @classmethod
    def changeCurrency(cls,x,y):
        return cls(x+y)
class Yen(Currency):
    def __int__(self,amount):
        self.amount=amount
        self.symbol="¥"
    def __repr__(self):
        return f"Currency class  Yen:{self.amount}"
print(Yen.changeCurrency(200,40))
        

Currency class  Yen:240


Create a class with a instance variable intilaized to zero. Create a dunder method next which generates values till 10

In [34]:
class Gen:
    def __init__(self):
        self.num=0
    def __iter__(self):
        return self
    def __next__(self):
        if self.num>10:
            raise StopIteration
        else:
            x=self.num
            self.num+=1
            return x
        
g=Gen()
for i in g:
    print(i)

0
1
2
3
4
5
6
7
8
9
10


Create a user defined exception:
In case the first value is less than the second value raise a BigNumber exception
otherwise raise smallNumber exception
and also handle those exception

In [38]:
class bigNumber(Exception):
    pass
class smallNumber(Exception):
    pass
try:
    a=int(input("enter 1st num"))
    b=int(input("enter 2nd num"))
    if a<b:
        raise bigNumber
    else:
        raise smallNumber
except bigNumber:
    print(f"{b} is larger than {a}")
except smallNumber:
    print(f"{a} is smaller than {b}")
    

enter 1st num2
enter 2nd num4
4 is larger than 2


In [6]:
def a(l):
    print(f' id of l in a {id(l)}')
    l[0] = 1
    print("\nValue of l = {0} in a()".format(l))

def b(l):
    print(f'before {id(l)}')
    l = l+[9]
    print(f'after {id(l)}')
    print("\nValue of l = {0} in b()".format(l))

l = [0]
print(f'id of l outside func {id(l)}')
a(l)
print("\nValue of l = {0} after executing a()".format(l))
b(l)
print("\nValue of l = {0} after executing b()".format(l))

id of l outside func 2284099434688
 id of l in a 2284099434688

Value of l = [1] in a()

Value of l = [1] after executing a()
before 2284099434688
after 2284099435840

Value of l = [1, 9] in b()

Value of l = [1] after executing b()


In [16]:
a=[10]
print(a,id(a))
a.append([20])
print(a,id(a))

[10] 2284099186368
[10, [20]] 2284099186368


In [29]:
a = "python is cool"
print(id(a))
b = "python is cool"
print(id(b))
a is b


2284099258288
2284100272176


False

In [22]:
a = "python"
print(id(a))
b = "python"
print(id(b))
a is b

2284064120944
2284064120944


True

In [28]:
g=iter(range(0,10))
next(g)

0

In [40]:
#decorator function
def B(func):
    print("Before executing inner")
    def inner():
        """ we are inside inner """
        print("Inside inner function")
        func()
        return "Decoration completed"
    return inner
@B
def A():
    """ we are inside A """
    print("A is being decorated")
@B
def C():
    print("Inside C function")
# A=B(A)
# print(A())
print(A())


print(C())

Before executing inner
Before executing inner
Inside inner function
A is being decorated
Decoration completed
Inside inner function
Inside C function
Decoration completed


In [34]:
print(A.__name__)

inner


In [37]:
print(A.__doc__)

 we are inside inner 


As currently, the decorated function holds the reference of wrapper function, if we try to print the doc string of the decorated function, we will get the docstring  of <b>wrapper</b>function.
To get the docstring of decorated function,from functools import

In [41]:
def decorator(func):
    def wrapper(*args,**kwargs):
        print("wrapper called")
        func(*args)
    return wrapper

@decorator       
def A(age):
    print("Inside A ",age)
    
@decorator
def B(name,age):
    print("Inside B",name,age)

print(A(10))
print(B("Zee",30))


wrapper called
Inside A  10
None
wrapper called
Inside B Zee 30
None


In [69]:
l=[{'user':"Tushar","accesslevel":"Administrator"}]

def passwordgen(func):
    def wrapper(*args,**kwargs):
        func(*args,**kwargs)
        for i in args:
            if i[0].get("user")=="Tushar":
                print("Your password is 1234")
            else:
                print("Access Denied")
    return wrapper
    
    
@passwordgen    
def A(l):
    d=l[0]
    print(f"Hey user {d['user']}")
print(A(l))   

Hey user Tushar
Your password is 1234
None


In [ ]:
# def decorator(*args,**kwargs):
#     print("Inside decorator")
#     def inner(func):
#         print("Inside inner")
#         func()

In [75]:
from collections import Counter
a=[1,2,4,1,2,3,2,1,4]
print(Counter(a))
b={'A':3,'B':2,'c':1}
print(Counter(b))
print(Counter(A=1,B=2,c=1))


Counter({1: 3, 2: 3, 4: 2, 3: 1})
Counter({'A': 3, 'B': 2, 'c': 1})
Counter({'B': 2, 'A': 1, 'c': 1})


In [85]:
x=[('a',10),('b',10),('a',20),('d',50),('a',60)]
d={}
for i in x:
    if i[0] not in d:
        d[i[0]]=[]
        d[i[0]].append(i[1])
    else:
        d[i[0]].append(i[1])
print(d)

{'a': [10, 20, 60], 'b': [10], 'd': [50]}


In [88]:
import numpy as np
h=[10,20,30,60]
np_h=np.array(h)

In [90]:
type(np_h)

numpy.ndarray

In [91]:
np_h*2

array([ 20,  40,  60, 120])

In [93]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(a1+a2)

[5 7 9]


In [107]:
x=np.array({1,2,3,1.2,1,2.0},dtype=object)
x

array({1, 2, 3, 1.2}, dtype=object)

In [111]:
heights=np.array([1,2,3,4,5])
len(heights)
heights.size
heights.shape

(5,)

In [124]:
a=np.array([2,3,4,5,7,10])
b=np.array([3,4,5,6,])
a[(a>2) &(a<7)]

array([3, 4, 5])

In [125]:
max(a)

10

In [126]:
a.max()

10

In [127]:
min(a)

2

In [129]:
b.mean()

4.5

In [139]:
x=np.array([(1,2,3),(3,4,5),(5,6,7),(7,8,9)])
x.ndim

2

In [133]:
x.dtype

dtype('int32')

In [142]:
y=x*[2,3,4]
y

array([[ 2,  6, 12],
       [ 6, 12, 20],
       [10, 18, 28],
       [14, 24, 36]])

In [143]:
x

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [149]:
z=np.array([(1,2),(3,4),(5,6),(7,8)])
z[0:3:2,0:2]

array([[1, 2],
       [5, 6]])

In [151]:
z[0,1]

2