Create 2 matrices. The matrices should have same dimension and call matrix+matrix2

In [6]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[5,6]])
c=a+b
c

array([[ 5,  7],
       [ 8, 10]])

In [7]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [9]:
x=np.arange(2,26,2).reshape(3,4)
x

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [12]:
for i in np.nditer(x):
    print(i)
y=x.T
print(y)

2
4
6
8
10
12
14
16
18
20
22
24
[[ 2 10 18]
 [ 4 12 20]
 [ 6 14 22]
 [ 8 16 24]]


In [13]:
import pandas as pd

In [20]:
data=pd.Series([10,2,3])
data

0    10
1     2
2     3
dtype: int64

In [15]:
data.index

RangeIndex(start=0, stop=3, step=1)

In [16]:
data.dtype

dtype('int64')

In [17]:
data.name

In [18]:
type(data)

pandas.core.series.Series

In [21]:
#returnns index of maximum element
data.idxmax()

0

In [22]:
pd.Series([1,2,3,4],index=["A","B","C","D"])

A    1
B    2
C    3
D    4
dtype: int64

In [27]:
#create series using numpy arrays
s=pd.Series(np.arange(2,10,2),index=["A","B","C","D"])

In [43]:
s.iloc[0],s.loc["A"],s.at["A"],s["A"]

(2, 2, 2, 2)

In [46]:
pd.Series({"User":[10,20,30],"name":["x","y"]})

User    [10, 20, 30]
name          [x, y]
dtype: object

In [49]:
pd.Series({"User":[10,20,30],"User":[10,20,3]})

User    [10, 20, 3]
dtype: object

In [51]:
df=pd.DataFrame({"name":['x','y'],"age":[10,20]})
df


name  age
0    x   10
1    y   20

In [52]:
df.index=["user1","user2"]

In [53]:
df

name  age
user1    x   10
user2    y   20

In [54]:
df.index

Index(['user1', 'user2'], dtype='object')

In [55]:
df["name"]

user1    x
user2    y
Name: name, dtype: object

In [57]:
type(df["name"])

pandas.core.series.Series

In [58]:
df["name"][0]

'x'

In [59]:
df.columns

Index(['name', 'age'], dtype='object')

In [60]:
df.columns=["names","ages"]
df

names  ages
user1     x    10
user2     y    20

In [69]:
df=pd.read_csv('pokemon_data.csv',)
df
type(df)
seriesdata=df.squeeze()

In [68]:
pwd

'C:\\Users\\miles.MILE-BL-4572-LA\\Desktop\\Python-notebooks'

In [70]:
df=pd.read_csv('pokemon_data.csv')
df

Pokemon     Type
0     Bulbasaur    Grass
1       Ivysaur    Grass
2      Venusaur    Grass
3    Charmander     Fire
4    Charmeleon     Fire
..          ...      ...
716     Yveltal     Dark
717     Zygarde   Dragon
718     Diancie     Rock
719       Hoopa  Psychic
720   Volcanion     Fire

[721 rows x 2 columns]

In [76]:
df.sort_values(by="Pokemon",ignore_index=True,ascending=False,inplace=True)
df

Pokemon     Type
0      Zygarde   Dragon
1     Zweilous     Dark
2        Zubat   Poison
3        Zorua     Dark
4      Zoroark     Dark
..         ...      ...
716  Aegislash    Steel
717   Accelgor      Bug
718      Absol     Dark
719       Abra  Psychic
720  Abomasnow    Grass

[721 rows x 2 columns]

In [77]:
df.head(5)

Pokemon    Type
0   Zygarde  Dragon
1  Zweilous    Dark
2     Zubat  Poison
3     Zorua    Dark
4   Zoroark    Dark

In [79]:
df.sort_index()

Pokemon     Type
0      Zygarde   Dragon
1     Zweilous     Dark
2        Zubat   Poison
3        Zorua     Dark
4      Zoroark     Dark
..         ...      ...
716  Aegislash    Steel
717   Accelgor      Bug
718      Absol     Dark
719       Abra  Psychic
720  Abomasnow    Grass

[721 rows x 2 columns]

In [80]:
df['Pokemon']

0        Zygarde
1       Zweilous
2          Zubat
3          Zorua
4        Zoroark
         ...    
716    Aegislash
717     Accelgor
718        Absol
719         Abra
720    Abomasnow
Name: Pokemon, Length: 721, dtype: object

In [87]:
s=pd.Series([1,2],index=["a","b"])
s
del s["a"]
s

b    2
dtype: int64

In [92]:
s=pd.Series([1,2],index=["a","b"])
s


a    1
b    2
dtype: int64

In [5]:
import numpy as np
print(np.ones((5,3),dtype='int'),np.zeros((5,3),dtype='int'),np.eye(3))

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]] [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
np.random.randint(low=0,high=10,size=10).reshape(5,2)

array([[5, 4],
       [1, 7],
       [1, 3],
       [6, 6],
       [3, 7]])

In [10]:
np.random.random(size=10)

array([0.64650242, 0.50570381, 0.78735424, 0.57319214, 0.29557085,
       0.33130992, 0.90615655, 0.02721317, 0.81399973, 0.35836223])

In [11]:
np.arange(6,66,6)

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

In [12]:
#Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside.
n=int(input())
a=np.zeros((n,n),dtype=int)
a[:,0]=1
a[:,-1]=1
a[0,:]=1
a[-1,:]=1
print(a)

4
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [13]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [14]:
np.linspace(2,20,10)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [15]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that pas

In [16]:
np.full(2,5)

array([5, 5])

In [17]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [21]:
np.full((4,4),[1,2,3,4])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [22]:
a=np.arange(1,11).reshape(5,2)
b=np.arange(11,21).reshape(5,2)
print(np.hstack((a,b)))

[[ 1  2 11 12]
 [ 3  4 13 14]
 [ 5  6 15 16]
 [ 7  8 17 18]
 [ 9 10 19 20]]


In [24]:
print(np.vstack((a,b)))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [25]:
help(np.unravel_index)

Help on function unravel_index in module numpy:

unravel_index(...)
    unravel_index(indices, shape, order='C')
    
    Converts a flat index or array of flat indices into a tuple
    of coordinate arrays.
    
    Parameters
    ----------
    indices : array_like
        An integer array whose elements are indices into the flattened
        version of an array of dimensions ``shape``. Before version 1.6.0,
        this function accepted just one index value.
    shape : tuple of ints
        The shape of the array to use for unraveling ``indices``.
    
        .. versionchanged:: 1.16.0
            Renamed from ``dims`` to ``shape``.
    
    order : {'C', 'F'}, optional
        Determines whether the indices should be viewed as indexing in
        row-major (C-style) or column-major (Fortran-style) order.
    
        .. versionadded:: 1.6.0
    
    Returns
    -------
    unraveled_coords : tuple of ndarray
        Each array in the tuple has the same shape as the ``indices``
 

In [26]:
#Reshape 2d array into 1 day
np.reshape(b,-1)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Stacking arrays
Description
Merge the three arrays provided to you to form a one 4x4 array.





Input:

Array 1: 3*3

[[7, 13, 14]

[18, 10, 17]

[11, 12, 19]]



Array 2: 1-D array

[16, 6, 1]



Array 3: 1*4 array

[[5, 8, 4, 3]]

Output:

[[7 13 14 5]

[18 10 17 8]

[11 12 19 4]

[16 6 1 3]]



In [29]:
a=np.array([[7, 13, 14],

[18, 10, 17],

[11, 12, 19]])
c=np.array([[5, 8, 4, 3]]).T
b=np.array([16, 6, 1])
v=np.vstack((a,b))
h=np.hstack((v,c))
h

array([[ 7, 13, 14,  5],
       [18, 10, 17,  8],
       [11, 12, 19,  4],
       [16,  6,  1,  3]])

In [30]:
np.add.accumulate(h) #columns wise accumulation has happened

array([[ 7, 13, 14,  5],
       [25, 23, 31, 13],
       [36, 35, 50, 17],
       [52, 41, 51, 20]], dtype=int32)

In [31]:
help(np.multiply.at)

Help on built-in function at:

at(...) method of numpy.ufunc instance
    at(a, indices, b=None, /)
    
    Performs unbuffered in place operation on operand 'a' for elements
    specified by 'indices'. For addition ufunc, this method is equivalent to
    ``a[indices] += b``, except that results are accumulated for elements that
    are indexed more than once. For example, ``a[[0,0]] += 1`` will only
    increment the first element once because of buffering, whereas
    ``add.at(a, [0,0], 1)`` will increment the first element twice.
    
    .. versionadded:: 1.8.0
    
    Parameters
    ----------
    a : array_like
        The array to perform in place operation on.
    indices : array_like or tuple
        Array like index object or slice object for indexing into first
        operand. If first operand has multiple dimensions, indices can be a
        tuple of array like index objects or slice objects.
    b : array_like
        Second operand for ufuncs requiring two operands. Op

In [38]:
import pandas as pd
a=[1,2,3]
b=['a','b','c']
df=pd.DataFrame((a,b),columns=["col1","col2","col3"])
df.index=["numbers","letters"]
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

InvalidIndexError: (slice(None, None, None), slice('col1', 'col3', None))